---
config:
  theme: redux-color
  look: neo
---

sequenceDiagram
  participant Client as Client
  participant Server as Server
  participant DB as DB

  Client ->> Server: POST /api/expenses (with form data)
  Server ->> Server: calculate splits based on expense data
  Server ->> DB: create new expense and all related splits in a transaction
  DB -->> Server: confirms creation of all records
  Server -->> Client: success


