---
config:
  theme: redux-color
  look: neo
---
sequenceDiagram
  participant Client as Client
  participant Server as Server
  participant DB as DB
  participant Liveblocks API as Liveblocks API
  Client ->> Server: POST /rooms/new (with initial room details)
  Server ->> Liveblocks API: create room with user permissions
  Liveblocks API -->> Server: returns new liveblocks room metadata
  Server ->> DB: store room metadata
  DB -->> Server: confirms record creation
  Server -->> Client: success
  Client ->> Client: redirect to home

